(()=>{
const host=document.querySelector('#clientAudit');if(!host)return;
const full=host.dataset.full==='true',base=location.pathname.startsWith('/property/')?'/property':'';
const labels={candidate:'На согласование',manual:'Личный ответ',pause:'Пауза',excluded:'Не отправлять',delivery:'Проверить доставку',locked:'Закрытый чат',review:'Нужен контекст',unclassified:'Без клиентской метки'};
let data,filter='candidate',query='';
async function request(path,body){const r=await fetch(base+path,{credentials:'same-origin',method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'Не удалось сохранить');return d}
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function button(parent,text,fn,cls){const b=el('button',text,cls);b.type='button';b.onclick=async()=>{b.disabled=true;try{await fn()}catch(e){alert(e.message)}finally{b.disabled=false}};parent.append(b);return b}
function render(){host.replaceChildren();const top=el('div',undefined,'row');top.append(el('h2',full?'Клиенты и следующий шаг':'Кому написать · ближайшая партия'));const a=el('a',full?'← Сегодня':'Все чаты и решения');a.href=full?'index.html':'followups.html';a.style.color='#c6ad80';top.append(a);host.append(top);
const s=data.stats;host.append(el('p',`Снимок ${data.snapshot} · ${s.all_chats} чата · ${s.labelled_clients} с клиентскими метками · ${s.ui_accessible||s.ui_checked} с доступной перепиской · ${s.ui_locked||0} закрытых`));
host.append(el('p',`${data.records.filter(r=>r.category==='candidate').length} кандидатов на согласование. Лимит — 45 серверных сообщений: 30 старым клиентам и 15 новым; ручные ответы отдельно. Отправка 09:00–18:00 Dubai.`));
const note=el('details');note.append(el('summary','Что удалось проверить'));for(const t of data.limitations)note.append(el('p',t));host.append(note);
if(!full){const personal=el('details');personal.append(el('summary','Отдельно ответить лично · '+data.records.filter(r=>r.category==='manual').length));for(const r of data.records.filter(r=>r.category==='manual'))personal.append(el('h3',r.name),el('p',r.reason));host.append(personal)}
const controls=el('div',undefined,'filters');if(full){for(const [k,v] of Object.entries(labels))button(controls,`${v} · ${data.records.filter(r=>r.category===k).length}`,()=>{filter=k;render()},filter===k?'gold':'');button(controls,'Все личные · '+s.individual_chats,()=>{filter='all';render()},filter==='all'?'gold':'')};host.append(controls);
if(full){const input=el('input');input.placeholder='Поиск по имени или номеру';input.value=query;input.oninput=()=>{query=input.value;renderRows()};host.append(input)}
const rowsHost=el('div');host.append(rowsHost);
function renderRows(){rowsHost.replaceChildren();const rows=data.records.filter(r=>(filter==='all'||r.category===filter)&&(!query||(r.name+' '+r.phone).toLowerCase().includes(query.toLowerCase())));const show=full?rows.slice(0,100):rows.slice(0,5);if(!show.length)rowsHost.append(el('p','Нет контактов по этому фильтру.'));
for(const r of show){const saved=data.review[r.id]||{};const card=el('article',undefined,'audit-client');const line=el('div',undefined,'row');line.append(el('h3',r.name),el('span',saved.decision==='include'?'Выбран':saved.decision==='skip'?'Пропустить':labels[r.category],'tag'));card.append(line,el('p',r.reason));const meta=el('small',`${r.source} · последнее исходящее ${r.last_date?r.last_date.slice(0,10):'не получено'} · ${r.history_count} записей`);meta.style.color='#929699';card.append(meta);
if(full&&r.incoming_excerpt){const incoming=el('details');incoming.append(el('summary','Последние доступные входящие'),el('p',r.incoming_excerpt));card.append(incoming)}
if(full&&r.last_text){const det=el('details');det.append(el('summary','Последнее исходящее · '+({sent:'отправлено',delivered:'доставлено',read:'прочитано',unknown:'статус неизвестен'}[r.provider_status]||r.provider_status)),el('p',r.last_text));card.append(det)}
if(r.category==='candidate'){const text=el('textarea');text.value=saved.text||r.text;text.setAttribute('aria-label','Сообщение: '+r.name);card.append(text);const actions=el('div',undefined,'row');button(actions,'Включить в черновик',async()=>{await request('/api/client-audit-review',{id:r.id,decision:'include',text:text.value});await load()},'gold');button(actions,'Не отправлять в этой партии',async()=>{await request('/api/client-audit-review',{id:r.id,decision:'skip',text:text.value});await load()});card.append(actions)}
else if(r.category==='manual')card.append(el('p',r.text||'Подготовить ответ по существу после проверки переписки.'));
rowsHost.append(card)}if(full&&rows.length>100)rowsHost.append(el('p',`Показано 100 из ${rows.length}. Уточните поиск.`));}renderRows();
const selected=data.records.filter(r=>data.review[r.id]?.decision==='include');const foot=el('div',undefined,'queue');foot.append(el('p',`Выбрано: ${selected.length} / 30. Решения и тексты сохраняются на сервере. Создание черновика не включает отправку.`));if(selected.length){const label=el('label');const check=el('input');check.type='checkbox';check.style.cssText='display:inline;width:auto;margin-right:8px';label.append(check,document.createTextNode('Проверил свежие ответы в WhatsApp у выбранных клиентов'));foot.append(label);button(foot,'Создать персональную рассылку',async()=>{if(!check.checked)throw Error('Сначала проверьте свежие ответы у выбранных клиентов');const d=await request('/api/client-audit-draft',{checked_replies:true});alert('Черновик '+d.campaign+' сохранён. Проверьте всех получателей и тексты в разделе «Сегодня».');location.href='index.html'},'gold')};host.append(foot);
}
async function load(){try{data=await request('/api/client-audit');render()}catch(e){host.replaceChildren(el('p',e.message))}}
const style=el('style');style.textContent='.audit-client{border-top:1px solid #303235;padding:20px 0}.audit-client h3{font-size:15px;font-weight:550;margin:0}.audit-client textarea{width:100%;min-height:92px;line-height:1.5;background:transparent;color:inherit;border:1px solid #929699;border-radius:8px;padding:12px;margin:14px 0}.filters{flex-wrap:wrap}details{margin:14px 0;color:#9a9d9f}summary{cursor:pointer}.audit-client .row{flex-wrap:wrap}';document.head.append(style);load();
})();
